### PR TITLE
Helm chart

### PR DESCRIPTION
**Pull request by alvarof2**
PR to add a Helm Chart for `safe-client-gateway` for Kubernetes deployments.

Also configures Cloud Build to:
- Build Docker image and deploy it to `us-central1-docker.pkg.dev/$PROJECT_ID/images/safe-client-gateway:$COMMIT_SHA` (Artifact Registry)
- Build Helm Chart as OCI image and deploy it to `us-central1-docker.pkg.dev/$PROJECT_ID/charts/safe-client-gateway:<CHART_VERSION>` (Artifact Registry)

Make sure these boxes are checked! 📦✅

- [ ] You are using the nightly version of rust `rustup default nighly`
- [ ] You have the latest version of `rustfmt` installed
```bash
$ rustup component add rustfmt
```
- [ ] You ran `cargo fmt` on the code base before submitting

### CODE REVIEW

**Comment by alvarof2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alvarof2** [comment]
recheckcla

**Comment by alvarof2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alvarof2** [comment]
Draft till we finish all conversations in [#17](https://github.com/celo-org/safe-config-service/pull/17) for `safe-config-service`

**Comment by alvarof2** [comment]
Also, for what I can see, the [CLA workflow](https://github.com/celo-org/safe-client-gateway/blob/d0539e5645f2d6fd6498817f64d7a10d7bde96a1/.github/workflows/cla.yml#L13) will not pass as commenting in the PR adds `\r\n\r\n` to the `github.event.comment.body` string, so these will never match `if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') ||... `

[https://api.github.com/repos/celo-org/safe-client-gateway/events](https://api.github.com/repos/celo-org/safe-client-gateway/events):

Screenshot from 2022-03-31 17-16-43

**Comment by alvarof2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alvarof2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alvarof2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alvarof2** [comment]
Using github cli creates the comment without `\r\n\r\n` but identifies `github-actions[bot]` [as a committer](https://github.com/celo-org/safe-client-gateway/runs/5777519297?check_suite_focus=true) that has not signed the CLA:

```
CLA Assistant GitHub Action has started
{ id: 'MDQ6VXNlcjM1NTA1MzAy', databaseId: 35505302, login: 'alvarof2' }
{ id: 'MDQ6VXNlcjM1NTA1MzAy', databaseId: 35505302, login: 'alvarof2' }
{ id: 'MDQ6VXNlcjM1NTA1MzAy', databaseId: 35505302, login: 'alvarof2' }
{ id: 'MDQ6VXNlcjM1NTA1MzAy', databaseId: 35505302, login: 'alvarof2' }
{ id: 'MDQ6VXNlcjM1NTA1MzAy', databaseId: 35505302, login: 'alvarof2' }
{
  id: 'MDM6Qm90NDE4OTgyODI=',
  databaseId: 4[18](https://github.com/celo-org/safe-client-gateway/runs/5777519297?check_suite_focus=true#step:2:18)98282,
  login: 'github-actions[bot]'
}
Adding empty commit for alvarof2 who has signed the CLA 
Error: Error occured when creating or editing the comments of the pull request: Reference does not exist
Error: committers of Pull Request number 2 have to sign the CLA
```

Probable need to bump the GA [version](https://github.com/celo-org/safe-client-gateway/blob/d0539e5645f2d6fd6498817f64d7a10d7bde96a1/.github/workflows/cla.yml#L15) in this fork to the same in the original [repo](https://github.com/gnosis/safe-client-gateway/blob/6e3fa0d5770d185bb0cbe27185d6b33641143b2e/.github/workflows/cla.yml#L15) (maybe even more changes)

**Comment by alvarof2** [comment]
Finally made it work by force pushing prior to the `github-actions[bot]` and still recognizes me as having signed the CLA (weird action).

To recap, CLA has to be signed with [GitHub cli](https://github.com/cli/cli) to avoid the  `\r\n\r\n` problem outlined above and then force-pushing to remove the `github-actions[bot]` commit.

Conclusion -> edit the GA workflow or try with the GA in the [original repo](`github-actions[bot]`)

Also, draft PR till [#17](https://github.com/celo-org/safe-config-service/pull/17) for `safe-config-service` is resolved.

**Review by lvpeschke — APPROVED** [review]

**Pull request merged**
